name: Update Repository Labels

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml
    - .github/workflows/labels.yml
  workflow_dispatch: # run manually from actions tab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Set permissions at the job level

jobs:
  update-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: crazy-max/ghaction-github-labeler@b54af0c25861143e7c8813d7cbbf46d2c341680c # v5.1.0
