name: Update Repository Labels

on:
  push:
    branches:
    - main
    paths:
    - .github/labels.yml
    - .github/workflows/labels.yml
  workflow_dispatch: # run manually from actions tab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {} # Set permissions at the job level

jobs:
  update-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: crazy-max/ghaction-github-labeler@31674a3852a9074f2086abcf1c53839d466a47e7 # v5.2.0
